name: locationtracker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cron: ^0.5.0
  flutter_local_notifications: ^6.0.0
  fluttertoast: ^8.0.9
  provider: ^6.0.3
  http: ^0.13.4
  google_fonts: ^3.0.1
  geolocator: ^7.7.1
  geocoding: ^2.0.4
  permission_handler: ^8.3.0
  timezone: ^0.7.0
  rxdart: ^0.27.5
  path_provider: ^2.0.11
  flutter_native_timezone: ^2.0.0
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
